/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

/**
 *
 * @author fchevalier
 */
public class F_MEDICAMENT extends javax.swing.JFrame {

    /**
     * Creates new form F_MEDICAMENTS
     */
    public F_MEDICAMENT() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCodeMedicaments = new javax.swing.JLabel();
        jLabelNomCommercialMedicaments = new javax.swing.JLabel();
        jLabelFamilleMedicaments = new javax.swing.JLabel();
        jLabelCompositionMedicaments = new javax.swing.JLabel();
        jLabelEffetsIndésirablesMedicaments = new javax.swing.JLabel();
        jLabelContreIndicationMedicaments = new javax.swing.JLabel();
        jLabelPrixEchantillonsMedicaments = new javax.swing.JLabel();
        jTextFieldTitre = new javax.swing.JTextField();
        jTextFieldCodeMedicaments = new javax.swing.JTextField();
        jTextFieldNomCommercialMedicaments = new javax.swing.JTextField();
        jTextFieldCompositionMedicaments = new javax.swing.JTextField();
        jTextFieldEffetsIndesirablesMedicaments = new javax.swing.JTextField();
        jTextFieldContreIndicationsMedicaments = new javax.swing.JTextField();
        jTextFieldPrixEchantillonsMedicaments = new javax.swing.JTextField();
        jComboBoxFamilleMedicaments = new javax.swing.JComboBox<>();
        jButtonPrécédentMedicaments = new javax.swing.JButton();
        jButtonSuivantMedicaments = new javax.swing.JButton();
        jButtonFermerMedicaments = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);

        jLabelCodeMedicaments.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelCodeMedicaments.setForeground(new java.awt.Color(51, 51, 153));
        jLabelCodeMedicaments.setText("Code");
        getContentPane().add(jLabelCodeMedicaments);
        jLabelCodeMedicaments.setBounds(22, 60, 60, 15);

        jLabelNomCommercialMedicaments.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelNomCommercialMedicaments.setForeground(new java.awt.Color(51, 51, 153));
        jLabelNomCommercialMedicaments.setText("Nom commercial");
        getContentPane().add(jLabelNomCommercialMedicaments);
        jLabelNomCommercialMedicaments.setBounds(22, 98, 100, 15);

        jLabelFamilleMedicaments.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelFamilleMedicaments.setForeground(new java.awt.Color(51, 51, 153));
        jLabelFamilleMedicaments.setText("Famille");
        getContentPane().add(jLabelFamilleMedicaments);
        jLabelFamilleMedicaments.setBounds(22, 138, 70, 15);

        jLabelCompositionMedicaments.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelCompositionMedicaments.setForeground(new java.awt.Color(51, 51, 153));
        jLabelCompositionMedicaments.setText("Composition");
        getContentPane().add(jLabelCompositionMedicaments);
        jLabelCompositionMedicaments.setBounds(22, 176, 100, 15);

        jLabelEffetsIndésirablesMedicaments.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelEffetsIndésirablesMedicaments.setForeground(new java.awt.Color(51, 51, 153));
        jLabelEffetsIndésirablesMedicaments.setText("Effets indésirables");
        getContentPane().add(jLabelEffetsIndésirablesMedicaments);
        jLabelEffetsIndésirablesMedicaments.setBounds(20, 230, 130, 40);

        jLabelContreIndicationMedicaments.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelContreIndicationMedicaments.setForeground(new java.awt.Color(51, 51, 153));
        jLabelContreIndicationMedicaments.setText("Contre Indications");
        getContentPane().add(jLabelContreIndicationMedicaments);
        jLabelContreIndicationMedicaments.setBounds(20, 350, 120, 15);

        jLabelPrixEchantillonsMedicaments.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelPrixEchantillonsMedicaments.setForeground(new java.awt.Color(51, 51, 153));
        jLabelPrixEchantillonsMedicaments.setText("Prix Echantillons");
        getContentPane().add(jLabelPrixEchantillonsMedicaments);
        jLabelPrixEchantillonsMedicaments.setBounds(20, 410, 100, 15);

        jTextFieldTitre.setEditable(false);
        jTextFieldTitre.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldTitre.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jTextFieldTitre.setForeground(new java.awt.Color(51, 51, 153));
        jTextFieldTitre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldTitre.setText("MEDICAMENTS");
        jTextFieldTitre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTitreActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldTitre);
        jTextFieldTitre.setBounds(22, 19, 720, 28);

        jTextFieldCodeMedicaments.setEditable(false);
        jTextFieldCodeMedicaments.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextFieldCodeMedicaments);
        jTextFieldCodeMedicaments.setBounds(160, 60, 140, 20);
        getContentPane().add(jTextFieldNomCommercialMedicaments);
        jTextFieldNomCommercialMedicaments.setBounds(160, 100, 140, 20);
        getContentPane().add(jTextFieldCompositionMedicaments);
        jTextFieldCompositionMedicaments.setBounds(160, 170, 463, 20);
        getContentPane().add(jTextFieldEffetsIndesirablesMedicaments);
        jTextFieldEffetsIndesirablesMedicaments.setBounds(160, 230, 460, 80);
        getContentPane().add(jTextFieldContreIndicationsMedicaments);
        jTextFieldContreIndicationsMedicaments.setBounds(160, 340, 463, 49);

        jTextFieldPrixEchantillonsMedicaments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrixEchantillonsMedicamentsActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldPrixEchantillonsMedicaments);
        jTextFieldPrixEchantillonsMedicaments.setBounds(160, 410, 59, 20);

        jComboBoxFamilleMedicaments.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBoxFamilleMedicaments);
        jComboBoxFamilleMedicaments.setBounds(160, 140, 56, 20);

        jButtonPrécédentMedicaments.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonPrécédentMedicaments.setForeground(new java.awt.Color(51, 51, 153));
        jButtonPrécédentMedicaments.setText("Précédent");
        getContentPane().add(jButtonPrécédentMedicaments);
        jButtonPrécédentMedicaments.setBounds(80, 460, 100, 23);

        jButtonSuivantMedicaments.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonSuivantMedicaments.setForeground(new java.awt.Color(51, 51, 153));
        jButtonSuivantMedicaments.setText("Suivant");
        getContentPane().add(jButtonSuivantMedicaments);
        jButtonSuivantMedicaments.setBounds(190, 460, 80, 23);

        jButtonFermerMedicaments.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonFermerMedicaments.setForeground(new java.awt.Color(51, 51, 153));
        jButtonFermerMedicaments.setText("Fermer");
        getContentPane().add(jButtonFermerMedicaments);
        jButtonFermerMedicaments.setBounds(637, 460, 80, 23);

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\fchevalier\\Desktop\\gsb_logo.png")); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(-20, -20, 820, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldTitreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTitreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTitreActionPerformed

    private void jTextFieldPrixEchantillonsMedicamentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrixEchantillonsMedicamentsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrixEchantillonsMedicamentsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F_MEDICAMENT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F_MEDICAMENT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F_MEDICAMENT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F_MEDICAMENT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F_MEDICAMENT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFermerMedicaments;
    private javax.swing.JButton jButtonPrécédentMedicaments;
    private javax.swing.JButton jButtonSuivantMedicaments;
    private javax.swing.JComboBox<String> jComboBoxFamilleMedicaments;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabelCodeMedicaments;
    private javax.swing.JLabel jLabelCompositionMedicaments;
    private javax.swing.JLabel jLabelContreIndicationMedicaments;
    private javax.swing.JLabel jLabelEffetsIndésirablesMedicaments;
    private javax.swing.JLabel jLabelFamilleMedicaments;
    private javax.swing.JLabel jLabelNomCommercialMedicaments;
    private javax.swing.JLabel jLabelPrixEchantillonsMedicaments;
    private javax.swing.JTextField jTextFieldCodeMedicaments;
    private javax.swing.JTextField jTextFieldCompositionMedicaments;
    private javax.swing.JTextField jTextFieldContreIndicationsMedicaments;
    private javax.swing.JTextField jTextFieldEffetsIndesirablesMedicaments;
    private javax.swing.JTextField jTextFieldNomCommercialMedicaments;
    private javax.swing.JTextField jTextFieldPrixEchantillonsMedicaments;
    private javax.swing.JTextField jTextFieldTitre;
    // End of variables declaration//GEN-END:variables
}
