/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

/**
 *
 * @author fchevalier
 */
public class F_MEDICAMENT extends javax.swing.JFrame {

    /**
     * Creates new form F_MEDICAMENTS
     */
    public F_MEDICAMENT() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldTitre = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jComboBoxFamille = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);

        jLabel1.setText("Code");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(22, 60, 25, 14);

        jLabel2.setText("Nom commercial");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(22, 98, 76, 14);

        jLabel3.setText("Famille");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(22, 138, 32, 14);

        jLabel4.setText("Composition");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(22, 176, 58, 14);

        jLabel5.setText("Effets indésirables");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(22, 223, 88, 14);

        jLabel6.setText("Contre Indications");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(22, 285, 88, 14);

        jLabel7.setText("Prix Echantillons");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(22, 357, 77, 14);

        jTextFieldTitre.setEditable(false);
        jTextFieldTitre.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldTitre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldTitre.setText("MEDICAMENTS");
        jTextFieldTitre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTitreActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldTitre);
        jTextFieldTitre.setBounds(22, 19, 595, 20);

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextField1);
        jTextField1.setBounds(128, 57, 140, 20);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(128, 95, 140, 20);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(128, 173, 463, 20);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(128, 223, 463, 42);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(128, 291, 463, 49);

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField7);
        jTextField7.setBounds(128, 358, 59, 20);

        jComboBoxFamille.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBoxFamille);
        jComboBoxFamille.setBounds(128, 135, 56, 20);

        jButton1.setText("Précédent");
        getContentPane().add(jButton1);
        jButton1.setBounds(90, 396, 81, 23);

        jButton2.setText("Suivant");
        getContentPane().add(jButton2);
        jButton2.setBounds(189, 396, 69, 23);

        jButton3.setText("Fermer");
        getContentPane().add(jButton3);
        jButton3.setBounds(507, 396, 67, 23);

        jLabel8.setText("bfgb");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(480, 80, 90, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldTitreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTitreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTitreActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F_MEDICAMENT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F_MEDICAMENT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F_MEDICAMENT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F_MEDICAMENT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F_MEDICAMENT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBoxFamille;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextFieldTitre;
    // End of variables declaration//GEN-END:variables
}
