/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import javax.swing.DefaultCellEditor;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author latatiasteph
 */
public class RapportsVisite extends javax.swing.JFrame {

    /**
     * Creates new form RapportsVisite
     */
    public RapportsVisite() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxTableau = new javax.swing.JComboBox();
        jTextFieldTitreRapportVisite = new javax.swing.JTextField();
        jLabelRapportsVisiteNumeroRapport = new javax.swing.JLabel();
        jLabelRapportsVisitePraticien = new javax.swing.JLabel();
        jLabelRapportsVisiteDateRapport = new javax.swing.JLabel();
        jLabelRapportsVisiteMotifVisite = new javax.swing.JLabel();
        jLabelRapportsVisiteBilan = new javax.swing.JLabel();
        jComboBoxRapportsVisitePraticien = new javax.swing.JComboBox<String>();
        jButtonRapportsVisiteDetails = new javax.swing.JButton();
        jTextFieldRapportsVisiteDateRapport = new javax.swing.JTextField();
        jTextFieldRapportsVisiteMotifVisite = new javax.swing.JTextField();
        jTextFieldRapportsVisiteBilan = new javax.swing.JTextField();
        jButtonRapportsVisitePrécédent = new javax.swing.JButton();
        jButtonRapportsVisiteSuivant = new javax.swing.JButton();
        jButtonRapportsVisiteNouveau = new javax.swing.JButton();
        jTextFieldRapportsVisiteNumeroRapport = new javax.swing.JTextField();
        jButtonRapportsVisiteFermer = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabelRapportsVisiteLogo = new javax.swing.JLabel();

        jComboBoxTableau.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldTitreRapportVisite.setEditable(false);
        jTextFieldTitreRapportVisite.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jTextFieldTitreRapportVisite.setForeground(new java.awt.Color(51, 51, 153));
        jTextFieldTitreRapportVisite.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldTitreRapportVisite.setText("RAPPORTS DE VISITE");
        getContentPane().add(jTextFieldTitreRapportVisite, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 570, -1));

        jLabelRapportsVisiteNumeroRapport.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelRapportsVisiteNumeroRapport.setForeground(new java.awt.Color(160, 160, 160));
        jLabelRapportsVisiteNumeroRapport.setText("NumeroRapport");
        getContentPane().add(jLabelRapportsVisiteNumeroRapport, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabelRapportsVisitePraticien.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelRapportsVisitePraticien.setForeground(new java.awt.Color(51, 51, 153));
        jLabelRapportsVisitePraticien.setText("Praticien");
        getContentPane().add(jLabelRapportsVisitePraticien, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 79, -1, -1));

        jLabelRapportsVisiteDateRapport.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelRapportsVisiteDateRapport.setForeground(new java.awt.Color(51, 51, 153));
        jLabelRapportsVisiteDateRapport.setText("Date Rapport");
        getContentPane().add(jLabelRapportsVisiteDateRapport, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 118, -1, -1));

        jLabelRapportsVisiteMotifVisite.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelRapportsVisiteMotifVisite.setForeground(new java.awt.Color(51, 51, 153));
        jLabelRapportsVisiteMotifVisite.setText("Motif Visite");
        getContentPane().add(jLabelRapportsVisiteMotifVisite, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 152, -1, -1));

        jLabelRapportsVisiteBilan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelRapportsVisiteBilan.setForeground(new java.awt.Color(51, 51, 153));
        jLabelRapportsVisiteBilan.setText("BILAN");
        getContentPane().add(jLabelRapportsVisiteBilan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jComboBoxRapportsVisitePraticien.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBoxRapportsVisitePraticien, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 77, 150, -1));

        jButtonRapportsVisiteDetails.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButtonRapportsVisiteDetails.setForeground(new java.awt.Color(51, 51, 153));
        jButtonRapportsVisiteDetails.setText("Détails");
        getContentPane().add(jButtonRapportsVisiteDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 77, -1, -1));
        getContentPane().add(jTextFieldRapportsVisiteDateRapport, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 116, 75, -1));
        getContentPane().add(jTextFieldRapportsVisiteMotifVisite, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 150, 150, -1));
        getContentPane().add(jTextFieldRapportsVisiteBilan, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 193, 174, 83));

        jButtonRapportsVisitePrécédent.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonRapportsVisitePrécédent.setForeground(new java.awt.Color(51, 51, 153));
        jButtonRapportsVisitePrécédent.setText("Précédent");
        getContentPane().add(jButtonRapportsVisitePrécédent, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, -1));

        jButtonRapportsVisiteSuivant.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonRapportsVisiteSuivant.setForeground(new java.awt.Color(51, 51, 153));
        jButtonRapportsVisiteSuivant.setText("Suivant");
        getContentPane().add(jButtonRapportsVisiteSuivant, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, -1, -1));

        jButtonRapportsVisiteNouveau.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonRapportsVisiteNouveau.setForeground(new java.awt.Color(51, 51, 153));
        jButtonRapportsVisiteNouveau.setText("Nouveau");
        getContentPane().add(jButtonRapportsVisiteNouveau, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, -1, -1));

        jTextFieldRapportsVisiteNumeroRapport.setEditable(false);
        jTextFieldRapportsVisiteNumeroRapport.setForeground(new java.awt.Color(160, 160, 160));
        jTextFieldRapportsVisiteNumeroRapport.setText("(NuméroAuto)");
        getContentPane().add(jTextFieldRapportsVisiteNumeroRapport, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        jButtonRapportsVisiteFermer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonRapportsVisiteFermer.setForeground(new java.awt.Color(51, 51, 153));
        jButtonRapportsVisiteFermer.setText("Fermer");
        getContentPane().add(jButtonRapportsVisiteFermer, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, -1, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Médicaments", "Nb. Echantillons"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setCellEditor(new DefaultCellEditor(jComboBoxTableau));
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 310, 70));

        jLabelRapportsVisiteLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vue/gh,hgfb.png"))); // NOI18N
        getContentPane().add(jLabelRapportsVisiteLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RapportsVisite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RapportsVisite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RapportsVisite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RapportsVisite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RapportsVisite().setVisible(true);
            }
        });
    }

    public JButton getjButtonRapportsVisiteDetails() {
        return jButtonRapportsVisiteDetails;
    }

    public JButton getjButtonRapportsVisiteFermer() {
        return jButtonRapportsVisiteFermer;
    }

    public JButton getjButtonRapportsVisiteNouveau() {
        return jButtonRapportsVisiteNouveau;
    }

    public JButton getjButtonRapportsVisitePrécédent() {
        return jButtonRapportsVisitePrécédent;
    }

    public JButton getjButtonRapportsVisiteSuivant() {
        return jButtonRapportsVisiteSuivant;
    }

    public JComboBox<String> getjComboBoxRapportsVisitePraticien() {
        return jComboBoxRapportsVisitePraticien;
    }

    public JTextField getjTextFieldRapportsVisiteBilan() {
        return jTextFieldRapportsVisiteBilan;
    }

    public JTextField getjTextFieldRapportsVisiteDateRapport() {
        return jTextFieldRapportsVisiteDateRapport;
    }

    public JTextField getjTextFieldRapportsVisiteMotifVisite() {
        return jTextFieldRapportsVisiteMotifVisite;
    }

    public JTextField getjTextFieldRapportsVisiteNumeroRapport() {
        return jTextFieldRapportsVisiteNumeroRapport;
    }

    public JTextField getjTextFieldTitreRapportVisite() {
        return jTextFieldTitreRapportVisite;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRapportsVisiteDetails;
    private javax.swing.JButton jButtonRapportsVisiteFermer;
    private javax.swing.JButton jButtonRapportsVisiteNouveau;
    private javax.swing.JButton jButtonRapportsVisitePrécédent;
    private javax.swing.JButton jButtonRapportsVisiteSuivant;
    private javax.swing.JComboBox<String> jComboBoxRapportsVisitePraticien;
    private javax.swing.JComboBox jComboBoxTableau;
    private javax.swing.JLabel jLabelRapportsVisiteBilan;
    private javax.swing.JLabel jLabelRapportsVisiteDateRapport;
    private javax.swing.JLabel jLabelRapportsVisiteLogo;
    private javax.swing.JLabel jLabelRapportsVisiteMotifVisite;
    private javax.swing.JLabel jLabelRapportsVisiteNumeroRapport;
    private javax.swing.JLabel jLabelRapportsVisitePraticien;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextFieldRapportsVisiteBilan;
    private javax.swing.JTextField jTextFieldRapportsVisiteDateRapport;
    private javax.swing.JTextField jTextFieldRapportsVisiteMotifVisite;
    private javax.swing.JTextField jTextFieldRapportsVisiteNumeroRapport;
    private javax.swing.JTextField jTextFieldTitreRapportVisite;
    // End of variables declaration//GEN-END:variables
}
